@startuml eHealthSUpermarket

class comercio {
idComercio
nombreComercio
telefono
CIF
}

class usuario {
idusuario
==
idComercio
}

class producto {
idProducto
nombreProducto
codigoBarras
fabricante
teléfono
}

class intolerancia {
idIntolerancia
nombreIntolerancia
}

class intoleranciasUsuario {
idintoleranciaUsuario
==
idIntolerancia
idUsuario
}

class ingrediente{
idIngrediente
nombreIngrediente
==
idIntolerancia
}

class productosusuario{
idProductoUsuario
==
idProducto
idUsuario
}

class ingredientesProducto{
idIngredienteProducto
==
idIngrediente
IdProducto
}

intolerancia "1" -- "*" ingrediente
comercio "1" -- "*" usuario
ingrediente "1" -- "*" ingredientesProducto
intolerancia "1" -- "*" intoleranciasUsuario
usuario "1" -- "*" intoleranciasUsuario
usuario "1" -- "*" productosusuario
producto "1" -- "*" productosusuario
producto "1" -- "*" ingredientesProducto


@enduml